plugins {
    id 'application'
}

application {
    mainClass = 'Main'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of 21
        vendor = JvmVendorSpec.ADOPTIUM
    }
}

repositories {
    mavenCentral()
}

dependencies {
    /*
    For logging, code to slf4j API only.
    At runtime, choose your implementation (logback is just an example).
     */
    implementation 'org.slf4j:slf4j-api:latest.release'
    runtimeOnly 'ch.qos.logback:logback-classic:latest.release'

    /*
    Bridge any other logging frameworks (used by any dependencies) to slf4j.
    https://www.slf4j.org/legacy.html "SLF4J bound to logback-classic with
    redirection of commons-logging, log4j and java.util.logging to SLF4J"
     */
    /* Jakarta Commons Logging. Also need to exclude 'commons-logging'. */
    runtimeOnly 'org.slf4j:jcl-over-slf4j:latest.release'
    /* Apache Log4J. */
    runtimeOnly 'org.slf4j:log4j-over-slf4j:latest.release'
    /* java.util.logging (JUL). Also need to use SLF4JBridgeHandler. */
    implementation 'org.slf4j:jul-to-slf4j:latest.release'

    /*
    Useful utility library Guava.
     */
    implementation 'com.google.guava:guava:latest.release'

    testImplementation 'org.junit.jupiter:junit-jupiter:latest.release'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
        showStandardStreams = true
    }
}
